source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use postgress as the database for Active record
gem 'pg'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# jQuery optimization for turbolinks
gem 'jquery-turbolinks'

# Build JSON APIs wgiith ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
gem 'bcrypt-ruby', :require => 'bcrypt'

# File upload
gem 'carrierwave'
gem 'rmagick'
gem 'jquery-fileupload-rails'

# CKEditor
gem 'ckeditor'
gem 'mini_magick'

# Ancestry
gem 'ancestry'

# Tagging
gem 'acts-as-taggable-on'

# Custom URLs
gem 'friendly_id', '5.0.0.rc2'

# Paginate
gem 'will_paginate', '~> 3.0'
gem 'will_paginate-bootstrap'

# Use debugger
gem 'debugger', group: [:development, :test]

# Generate class diagrams
gem 'railroady'

# Schedualed events
gem 'whenever', :require => false

# Backwards compatibility with Rails 3
#gem 'protected_attributes'
